spring:
  application:
    name: api-gateway
server:
  port: 5555

zuul:
  routes:
    ribbon-consumer:
      path: /ribbon-consumer/**

    service-provider:
      path: /service-provider/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/