spring:
  application:
    name: eureka
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # 不将自己注册到一个注册中心上
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false # 是否从其他Eureka注册中心同步服务列表
  server:
    enable-self-preservation: false # 禁用自我保护机制



